# IS 362 Project 2
Sam Sikder

This project analyzes three datasets using Python and pandas.

Datasets used:
1. Best-Selling Video Games
2. World Series Champions
3. Countries by GDP (Nominal)

In [32]:
import pandas as pd

## Dataset 1: Best-Selling Video Games

This dataset lists the best-selling video games of all time along with their sales and platforms.

In [34]:
games = pd.read_csv("videogames.csv")
games.head()

   Rank       Title  Sales_Millions        Platform  Release_Year
0     1      Tetris           520.0  Multi-platform          1988
1     2   Minecraft           300.0  Multi-platform          2011
2     3       GTA V           185.0  Multi-platform          2013
3     4  Wii Sports            82.9             Wii          2006
4     5        PUBG            75.0  Multi-platform          2017

In [35]:
# Find the best selling game
games.sort_values(by="Sales_Millions", ascending=False)

   Rank       Title  Sales_Millions        Platform  Release_Year
0     1      Tetris           520.0  Multi-platform          1988
1     2   Minecraft           300.0  Multi-platform          2011
2     3       GTA V           185.0  Multi-platform          2013
3     4  Wii Sports            82.9             Wii          2006
4     5        PUBG            75.0  Multi-platform          2017

In [36]:
# Calculate average sales
games["Sales_Millions"].mean()

232.58

In [37]:
# Count how many games per platform
games["Platform"].value_counts()

Platform
Multi-platform    4
Wii               1
Name: count, dtype: int64

### Analysis

The dataset was loaded using pandas and examined using the `head()` function to preview the data.  
The data was sorted by sales to identify the best-selling video game.  
Additional analysis was performed to calculate the average sales and determine how many games appear on each platform.

## Dataset 2: World Series Champions

This dataset lists recent World Series champions along with the runner-up teams and number of games played.

In [40]:
world_series = pd.read_csv("worldseries.csv")

world_series.head()

   Year              Champion               RunnerUp Games
0  2023         Texas Rangers   Arizona Diamondbacks   4-1
1  2022        Houston Astros  Philadelphia Phillies   4-2
2  2021        Atlanta Braves         Houston Astros   4-2
3  2020   Los Angeles Dodgers         Tampa Bay Rays   4-2
4  2019  Washington Nationals         Houston Astros   4-3

In [41]:
# Count how many championships each team has
world_series["Champion"].value_counts()

Champion
Texas Rangers           1
Houston Astros          1
Atlanta Braves          1
Los Angeles Dodgers     1
Washington Nationals    1
Name: count, dtype: int64

### Analysis

The dataset was loaded using pandas and previewed using the `head()` function.  
The `value_counts()` function was used to determine how many times each team appears as a World Series champion.

## Dataset 3: Countries by GDP (Nominal)

This dataset lists several countries and their GDP values in trillions of U.S. dollars.

In [44]:
gdp = pd.read_csv("gdp.csv")

gdp.head()

   Rank        Country  GDP_Trillion_USD
0     1  United States              26.9
1     2          China              17.7
2     3        Germany               4.5
3     4          Japan               4.2
4     5          India               3.7

In [45]:
# Sort countries by GDP
gdp.sort_values(by="GDP_Trillion_USD", ascending=False)

   Rank        Country  GDP_Trillion_USD
0     1  United States              26.9
1     2          China              17.7
2     3        Germany               4.5
3     4          Japan               4.2
4     5          India               3.7

In [46]:
# Calculate average GDP
gdp["GDP_Trillion_USD"].mean()

11.4

### Analysis

The GDP dataset was loaded using pandas and previewed using the `head()` function.  
The data was sorted to identify the countries with the highest GDP values.  
The average GDP was also calculated to understand the overall scale of the economies included in the dataset.

## Conclusion

In this project, three datasets were analyzed using Python and the pandas library. 
The datasets included best-selling video games, World Series champions, and countries by GDP. 

The data was loaded from CSV files, previewed using the head() function, and analyzed 
using sorting, averages, and value counts. These steps demonstrate how pandas can be 
used to quickly explore and analyze structured datasets.