# Assignment 7 – Web APIs

Name: Sam Sikder 
Course: IS 362  
Date: April 18, 2026

For this assignment, I selected a New York Times API and used Python to retrieve JSON data and convert it into a pandas DataFrame.

## Importing Libraries

The requests library was used to connect to the API, and pandas was used to organize the JSON data into a DataFrame.

In [2]:
import requests
import pandas as pd

In [4]:
api_key = "zDwPms51NwgCbrPsIIIoBzdGmn7N8Bajhe0zoor9X6b7i7K8"

In [6]:
url = f"https://api.nytimes.com/svc/mostpopular/v2/viewed/7.json?api-key={api_key}"

response = requests.get(url)

response.status_code

200

In [8]:
data = response.json()

articles = data["results"]

df = pd.DataFrame(articles)

df.head()

,uri,url,id,asset_id,source,published_date,updated,section,subsection,nytdsection,...,byline,type,title,abstract,des_facet,org_facet,per_facet,geo_facet,media,eta_id
0,nyt://article/db1a6ed9-380c-5e9a-8d3c-914bde4d...,https://www.nytimes.com/2026/04/14/us/florida-...,100000010840508,100000010840508,New York Times,2026-04-14,2026-04-16 20:40:02,U.S.,,u.s.,...,By Vjosa Isai,Article,Surgeon Who Removed Wrong Organ From Patient I...,Dr. Thomas Shaknovsky tried to persuade his co...,"[Malpractice, Surgery and Surgeons, Deaths (Fa...",[],[],"[Miramar (Fla), Walton County (Fla)]","[{'type': 'image', 'subtype': 'photo', 'captio...",0
1,nyt://article/c6262605-4132-560e-a13d-328918cb...,https://www.nytimes.com/2026/04/14/us/politics...,100000010841613,100000010841613,New York Times,2026-04-14,2026-04-15 13:19:41,U.S.,Politics,u.s.,...,By Anton Troianovski,Article,Vance Says the Pope Should Be More Careful Whe...,"The vice president, who is Catholic, took issu...","[US and Israeli Attack on Iran (2026), United ...",[Roman Catholic Church],"[Leo XIV, Vance, J D, Trump, Donald J]",[Iran],"[{'type': 'image', 'subtype': 'photo', 'captio...",0
2,nyt://article/52e70095-83cd-51ce-ae58-74124639...,https://www.nytimes.com/2026/04/15/us/yale-rep...,100000010840797,100000010840797,New York Times,2026-04-15,2026-04-16 10:39:27,U.S.,,u.s.,...,By Alan Blinder,Article,Yale Report Finds Colleges Deserve Blame for H...,A 10-member committee offered a brutal assessm...,"[Colleges and Universities, Polls and Public O...",[Yale University],"[Trump, Donald J]",[United States],"[{'type': 'image', 'subtype': 'photo', 'captio...",0
3,nyt://article/082d1996-e31b-5e44-bb95-5340bb34...,https://www.nytimes.com/2026/04/18/us/politics...,100000010774581,100000010774581,New York Times,2026-04-18,2026-04-18 17:02:58,U.S.,Politics,u.s.,...,By Jodi Kantor and Adam Liptak,Article,The Inside Story of Five Days That Remade the ...,Secret memos obtained by The New York Times il...,"[United States Politics and Government, Decisi...","[Supreme Court (US), Environmental Protection ...","[Alito, Samuel A Jr, Breyer, Stephen G, Ginsbu...",[],"[{'type': 'image', 'subtype': 'photo', 'captio...",0
4,nyt://article/a1aaf500-1e41-5e31-91da-64d16a75...,https://www.nytimes.com/2026/04/17/opinion/laf...,100000010844525,100000010844525,New York Times,2026-04-17,2026-04-18 16:17:23,Opinion,,opinion,...,By M. Gessen,Article,A Stunning New Verdict Rewrites the Rules of C...,The profit motive was on trial. The verdict wa...,"[Decisions and Verdicts, War and Armed Conflic...","[Islamic State in Iraq and Syria (ISIS), Lafar...",[],"[Paris (France), Syria]","[{'type': 'image', 'subtype': 'photo', 'captio...",0

In [10]:
df = df[[
    "title",
    "abstract",
    "byline",
    "published_date",
    "section",
    "source",
    "url"
]]

df.head()

,title,abstract,byline,published_date,section,source,url
0,Surgeon Who Removed Wrong Organ From Patient I...,Dr. Thomas Shaknovsky tried to persuade his co...,By Vjosa Isai,2026-04-14,U.S.,New York Times,https://www.nytimes.com/2026/04/14/us/florida-...
1,Vance Says the Pope Should Be More Careful Whe...,"The vice president, who is Catholic, took issu...",By Anton Troianovski,2026-04-14,U.S.,New York Times,https://www.nytimes.com/2026/04/14/us/politics...
2,Yale Report Finds Colleges Deserve Blame for H...,A 10-member committee offered a brutal assessm...,By Alan Blinder,2026-04-15,U.S.,New York Times,https://www.nytimes.com/2026/04/15/us/yale-rep...
3,The Inside Story of Five Days That Remade the ...,Secret memos obtained by The New York Times il...,By Jodi Kantor and Adam Liptak,2026-04-18,U.S.,New York Times,https://www.nytimes.com/2026/04/18/us/politics...
4,A Stunning New Verdict Rewrites the Rules of C...,The profit motive was on trial. The verdict wa...,By M. Gessen,2026-04-17,Opinion,New York Times,https://www.nytimes.com/2026/04/17/opinion/laf...

## Summary

In this assignment, I used the New York Times Most Popular API to retrieve article data in JSON format. Using Python and the requests library, I accessed the API and converted the JSON response into a pandas DataFrame. The DataFrame organizes article information such as title, author, publication date, section, and URL.